<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PatientSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $clinic1 = DB::table('clinics')->where('slug', 'sharma-skin-hair')->value('id');
        $clinic2 = DB::table('clinics')->where('slug', 'activephysio-rehab')->value('id');
        $clinic3 = DB::table('clinics')->where('slug', 'brightsmile-dental')->value('id');

        if (!$clinic1 || !$clinic2 || !$clinic3) {
            $this->command->error('PatientSeeder: Clinics not found. Run ClinicSeeder first.');
            return;
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('patients')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        // Patients — 30 total; 12 for derma, 9 for physio, 9 for dental
        // Columns: clinic_id, name, dob, sex, phone, email, blood_group,
        //          abha_id (nullable), abha_address (nullable),
        //          abdm_consent_active, medical_history, family_history,
        //          visit_count, last_visit_date, created_at, updated_at

        $patients = [

            // ── Sharma Skin & Hair (clinic1) — 12 patients ───────────────────

            [
                'clinic_id'            => $clinic1,
                'name'                 => 'Priya Mehta',
                'dob'                  => '1991-04-15',
                'sex'                  => 'F',
                'phone'                => '+919823456780',
                'email'                => 'priya.mehta91@gmail.com',
                'blood_group'          => 'B+',
                'abha_id'              => '423112345601',
                'abha_address'         => 'priyamehta@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => ['Penicillin'],
                    'chronic_conditions'   => ['Psoriasis'],
                    'current_medications'  => ['Topical steroids'],
                ]),
                'family_history'       => json_encode(['psoriasis' => 'Mother']),
                'visit_count'          => 6,
                'last_visit_date'      => '2026-02-10',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic1,
                'name'                 => 'Ananya Patil',
                'dob'                  => '1998-09-22',
                'sex'                  => 'F',
                'phone'                => '+919765432109',
                'email'                => 'ananya.patil98@gmail.com',
                'blood_group'          => 'O+',
                'abha_id'              => null,
                'abha_address'         => null,
                'abdm_consent_active'  => false,
                'medical_history'      => json_encode([
                    'allergies'            => [],
                    'chronic_conditions'   => ['Acne Grade 3'],
                    'current_medications'  => [],
                ]),
                'family_history'       => null,
                'visit_count'          => 4,
                'last_visit_date'      => '2026-01-25',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic1,
                'name'                 => 'Vikram Shah',
                'dob'                  => '1974-03-08',
                'sex'                  => 'M',
                'phone'                => '+919654321098',
                'email'                => 'vikram.shah74@yahoo.com',
                'blood_group'          => 'A+',
                'abha_id'              => '514223456702',
                'abha_address'         => 'vikramshah@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => [],
                    'chronic_conditions'   => ['Androgenetic Alopecia'],
                    'current_medications'  => ['Minoxidil 5% solution'],
                ]),
                'family_history'       => json_encode(['alopecia' => 'Father, Paternal Uncle']),
                'visit_count'          => 8,
                'last_visit_date'      => '2026-03-01',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic1,
                'name'                 => 'Sunita Desai',
                'dob'                  => '1985-11-30',
                'sex'                  => 'F',
                'phone'                => '+919543210987',
                'email'                => 'sunita.desai@hotmail.com',
                'blood_group'          => 'AB+',
                'abha_id'              => '625334567803',
                'abha_address'         => 'sunitadesai@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => ['Sulfa drugs'],
                    'chronic_conditions'   => ['Melasma', 'Hypothyroidism'],
                    'current_medications'  => ['Levothyroxine 50mcg'],
                ]),
                'family_history'       => json_encode(['hypothyroidism' => 'Mother']),
                'visit_count'          => 5,
                'last_visit_date'      => '2026-02-18',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic1,
                'name'                 => 'Rohit Kulkarni',
                'dob'                  => '1995-06-17',
                'sex'                  => 'M',
                'phone'                => '+919432109876',
                'email'                => 'rohit.kulkarni95@gmail.com',
                'blood_group'          => 'O-',
                'abha_id'              => null,
                'abha_address'         => null,
                'abdm_consent_active'  => false,
                'medical_history'      => json_encode([
                    'allergies'            => [],
                    'chronic_conditions'   => ['Seborrheic Dermatitis'],
                    'current_medications'  => [],
                ]),
                'family_history'       => null,
                'visit_count'          => 2,
                'last_visit_date'      => '2026-01-10',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic1,
                'name'                 => 'Kaveri Iyer',
                'dob'                  => '1968-02-14',
                'sex'                  => 'F',
                'phone'                => '+919321098765',
                'email'                => 'kaveri.iyer@gmail.com',
                'blood_group'          => 'A-',
                'abha_id'              => '736445678904',
                'abha_address'         => 'kaveriyer@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => ['NSAIDs'],
                    'chronic_conditions'   => ['Vitiligo', 'Diabetes Type 2'],
                    'current_medications'  => ['Metformin 500mg', 'Tacrolimus 0.1% ointment'],
                ]),
                'family_history'       => json_encode(['vitiligo' => 'Brother', 'diabetes' => 'Father']),
                'visit_count'          => 12,
                'last_visit_date'      => '2026-03-10',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic1,
                'name'                 => 'Amit Jain',
                'dob'                  => '1990-08-05',
                'sex'                  => 'M',
                'phone'                => '+919210987654',
                'email'                => 'amit.jain90@gmail.com',
                'blood_group'          => 'B-',
                'abha_id'              => null,
                'abha_address'         => null,
                'abdm_consent_active'  => false,
                'medical_history'      => json_encode([
                    'allergies'            => [],
                    'chronic_conditions'   => ['Fungal Nail Infection (Onychomycosis)'],
                    'current_medications'  => ['Terbinafine 250mg'],
                ]),
                'family_history'       => null,
                'visit_count'          => 3,
                'last_visit_date'      => '2026-02-05',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic1,
                'name'                 => 'Pooja Nair',
                'dob'                  => '2003-12-28',
                'sex'                  => 'F',
                'phone'                => '+919198765432',
                'email'                => 'pooja.nair2003@gmail.com',
                'blood_group'          => 'O+',
                'abha_id'              => '847556789005',
                'abha_address'         => 'poojanair@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => ['Penicillin'],
                    'chronic_conditions'   => ['Atopic Dermatitis'],
                    'current_medications'  => ['Moisturiser', 'Topical steroid PRN'],
                ]),
                'family_history'       => json_encode(['atopy' => 'Mother (asthma)']),
                'visit_count'          => 4,
                'last_visit_date'      => '2026-03-05',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic1,
                'name'                 => 'Sandeep Banerjee',
                'dob'                  => '1978-07-19',
                'sex'                  => 'M',
                'phone'                => '+919087654321',
                'email'                => 'sandeep.banerjee78@gmail.com',
                'blood_group'          => 'AB-',
                'abha_id'              => '958667890106',
                'abha_address'         => 'sandeepbanerjee@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => [],
                    'chronic_conditions'   => ['Lichen Planus'],
                    'current_medications'  => [],
                ]),
                'family_history'       => null,
                'visit_count'          => 2,
                'last_visit_date'      => '2026-01-20',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic1,
                'name'                 => 'Deepa Verma',
                'dob'                  => '2001-03-12',
                'sex'                  => 'F',
                'phone'                => '+919176543210',
                'email'                => 'deepa.verma2001@gmail.com',
                'blood_group'          => 'B+',
                'abha_id'              => null,
                'abha_address'         => null,
                'abdm_consent_active'  => false,
                'medical_history'      => json_encode([
                    'allergies'            => [],
                    'chronic_conditions'   => ['Acne Grade 2', 'PCOS'],
                    'current_medications'  => ['OCP (Ethinylestradiol/Norethisterone)'],
                ]),
                'family_history'       => json_encode(['PCOS' => 'Mother']),
                'visit_count'          => 5,
                'last_visit_date'      => '2026-02-28',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic1,
                'name'                 => 'Harish Patel',
                'dob'                  => '1960-09-01',
                'sex'                  => 'M',
                'phone'                => '+919265432109',
                'email'                => 'harish.patel60@yahoo.com',
                'blood_group'          => 'A+',
                'abha_id'              => '069778901207',
                'abha_address'         => 'harishpatel@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => ['NSAIDs'],
                    'chronic_conditions'   => ['Psoriatic Arthritis', 'Hypertension'],
                    'current_medications'  => ['Methotrexate 15mg/week', 'Amlodipine 5mg'],
                ]),
                'family_history'       => json_encode(['psoriasis' => 'Father', 'hypertension' => 'Both parents']),
                'visit_count'          => 15,
                'last_visit_date'      => '2026-03-15',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic1,
                'name'                 => 'Lata Shinde',
                'dob'                  => '1955-05-25',
                'sex'                  => 'F',
                'phone'                => '+919354321098',
                'email'                => null,
                'blood_group'          => 'O+',
                'abha_id'              => '170889012308',
                'abha_address'         => 'latashinde@abdm',
                'abdm_consent_active'  => false,
                'medical_history'      => json_encode([
                    'allergies'            => ['Sulfa drugs'],
                    'chronic_conditions'   => ['Rosacea', 'Diabetes Type 2', 'Hypertension'],
                    'current_medications'  => ['Metformin 1g', 'Amlodipine 5mg'],
                ]),
                'family_history'       => json_encode(['diabetes' => 'Both parents']),
                'visit_count'          => 9,
                'last_visit_date'      => '2026-03-08',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],

            // ── ActivePhysio & Rehab (clinic2) — 9 patients ──────────────────

            [
                'clinic_id'            => $clinic2,
                'name'                 => 'Rajesh Kumar',
                'dob'                  => '1981-06-10',
                'sex'                  => 'M',
                'phone'                => '+919876012345',
                'email'                => 'rajesh.kumar81@gmail.com',
                'blood_group'          => 'B+',
                'abha_id'              => '281990123409',
                'abha_address'         => 'rajeshkumar@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => [],
                    'chronic_conditions'   => ['Knee Osteoarthritis (Bilateral Grade II)'],
                    'current_medications'  => ['Glucosamine 1500mg'],
                ]),
                'family_history'       => json_encode(['osteoarthritis' => 'Mother']),
                'visit_count'          => 18,
                'last_visit_date'      => '2026-03-20',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic2,
                'name'                 => 'Meera Kapoor',
                'dob'                  => '1988-01-18',
                'sex'                  => 'F',
                'phone'                => '+919765012345',
                'email'                => 'meera.kapoor88@gmail.com',
                'blood_group'          => 'A+',
                'abha_id'              => null,
                'abha_address'         => null,
                'abdm_consent_active'  => false,
                'medical_history'      => json_encode([
                    'allergies'            => [],
                    'chronic_conditions'   => ['Frozen Shoulder (Adhesive Capsulitis) — Left'],
                    'current_medications'  => [],
                ]),
                'family_history'       => null,
                'visit_count'          => 10,
                'last_visit_date'      => '2026-03-18',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic2,
                'name'                 => 'Suresh Naidu',
                'dob'                  => '1970-08-29',
                'sex'                  => 'M',
                'phone'                => '+919654012345',
                'email'                => 'suresh.naidu70@yahoo.com',
                'blood_group'          => 'O+',
                'abha_id'              => '392001234510',
                'abha_address'         => 'sureshnaidu@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => ['NSAIDs'],
                    'chronic_conditions'   => ['Lumbar Disc Herniation L4-L5', 'Hypertension'],
                    'current_medications'  => ['Amlodipine 5mg'],
                ]),
                'family_history'       => null,
                'visit_count'          => 22,
                'last_visit_date'      => '2026-03-22',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic2,
                'name'                 => 'Pallavi Rao',
                'dob'                  => '1993-12-03',
                'sex'                  => 'F',
                'phone'                => '+919543012345',
                'email'                => 'pallavi.rao93@gmail.com',
                'blood_group'          => 'AB+',
                'abha_id'              => null,
                'abha_address'         => null,
                'abdm_consent_active'  => false,
                'medical_history'      => json_encode([
                    'allergies'            => [],
                    'chronic_conditions'   => ['Plantar Fasciitis — Bilateral'],
                    'current_medications'  => [],
                ]),
                'family_history'       => null,
                'visit_count'          => 6,
                'last_visit_date'      => '2026-02-15',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic2,
                'name'                 => 'Gopal Menon',
                'dob'                  => '1965-04-07',
                'sex'                  => 'M',
                'phone'                => '+919432012345',
                'email'                => 'gopal.menon65@gmail.com',
                'blood_group'          => 'B-',
                'abha_id'              => '403112345611',
                'abha_address'         => 'gopalmenon@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => ['Penicillin'],
                    'chronic_conditions'   => ['Post-Stroke Hemiplegia — Left Side', 'Hypertension', 'Diabetes Type 2'],
                    'current_medications'  => ['Aspirin 75mg', 'Atorvastatin 20mg', 'Metformin 500mg'],
                ]),
                'family_history'       => json_encode(['hypertension' => 'Father', 'diabetes' => 'Mother']),
                'visit_count'          => 35,
                'last_visit_date'      => '2026-03-24',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic2,
                'name'                 => 'Reena Sharma',
                'dob'                  => '1975-10-14',
                'sex'                  => 'F',
                'phone'                => '+919321012345',
                'email'                => 'reena.sharma75@gmail.com',
                'blood_group'          => 'A-',
                'abha_id'              => '514223456712',
                'abha_address'         => 'reenasharma@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => [],
                    'chronic_conditions'   => ['Cervical Spondylosis C5-C6'],
                    'current_medications'  => [],
                ]),
                'family_history'       => null,
                'visit_count'          => 14,
                'last_visit_date'      => '2026-03-12',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic2,
                'name'                 => 'Dinesh Gujral',
                'dob'                  => '1958-02-20',
                'sex'                  => 'M',
                'phone'                => '+919210012345',
                'email'                => 'dinesh.gujral58@yahoo.com',
                'blood_group'          => 'O-',
                'abha_id'              => null,
                'abha_address'         => null,
                'abdm_consent_active'  => false,
                'medical_history'      => json_encode([
                    'allergies'            => ['Sulfa drugs'],
                    'chronic_conditions'   => ['Knee Replacement Post-Op Rehab', 'Diabetes Type 2'],
                    'current_medications'  => ['Metformin 1g', 'Warfarin (cardiologist supervised)'],
                ]),
                'family_history'       => json_encode(['diabetes' => 'Father']),
                'visit_count'          => 8,
                'last_visit_date'      => '2026-03-19',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic2,
                'name'                 => 'Swati Chavan',
                'dob'                  => '2000-07-07',
                'sex'                  => 'F',
                'phone'                => '+919098012345',
                'email'                => 'swati.chavan2000@gmail.com',
                'blood_group'          => 'B+',
                'abha_id'              => '625334567813',
                'abha_address'         => 'swatichavan@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => [],
                    'chronic_conditions'   => ['ACL Tear — Right Knee (Post Surgical Rehab)'],
                    'current_medications'  => [],
                ]),
                'family_history'       => null,
                'visit_count'          => 20,
                'last_visit_date'      => '2026-03-23',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic2,
                'name'                 => 'Naresh Tiwari',
                'dob'                  => '1982-11-11',
                'sex'                  => 'M',
                'phone'                => '+919187012345',
                'email'                => 'naresh.tiwari82@gmail.com',
                'blood_group'          => 'AB-',
                'abha_id'              => null,
                'abha_address'         => null,
                'abdm_consent_active'  => false,
                'medical_history'      => json_encode([
                    'allergies'            => [],
                    'chronic_conditions'   => ['Rotator Cuff Tear — Right Shoulder (Conservative)'],
                    'current_medications'  => [],
                ]),
                'family_history'       => null,
                'visit_count'          => 12,
                'last_visit_date'      => '2026-03-10',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],

            // ── BrightSmile Dental (clinic3) — 9 patients ────────────────────

            [
                'clinic_id'            => $clinic3,
                'name'                 => 'Arun Krishnan',
                'dob'                  => '1980-03-25',
                'sex'                  => 'M',
                'phone'                => '+919845112233',
                'email'                => 'arun.krishnan80@gmail.com',
                'blood_group'          => 'O+',
                'abha_id'              => '736445678914',
                'abha_address'         => 'arunkrishnan@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => [],
                    'chronic_conditions'   => ['Multiple Caries', 'Gingivitis'],
                    'current_medications'  => [],
                ]),
                'family_history'       => null,
                'visit_count'          => 7,
                'last_visit_date'      => '2026-02-20',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic3,
                'name'                 => 'Shalini Gupta',
                'dob'                  => '1994-06-15',
                'sex'                  => 'F',
                'phone'                => '+919844112233',
                'email'                => 'shalini.gupta94@gmail.com',
                'blood_group'          => 'A+',
                'abha_id'              => null,
                'abha_address'         => null,
                'abdm_consent_active'  => false,
                'medical_history'      => json_encode([
                    'allergies'            => ['Penicillin'],
                    'chronic_conditions'   => ['Malocclusion (Crowding)', 'Bruxism'],
                    'current_medications'  => [],
                ]),
                'family_history'       => null,
                'visit_count'          => 5,
                'last_visit_date'      => '2026-03-01',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic3,
                'name'                 => 'Vivek Prasad',
                'dob'                  => '1967-09-30',
                'sex'                  => 'M',
                'phone'                => '+919843112233',
                'email'                => 'vivek.prasad67@yahoo.com',
                'blood_group'          => 'B+',
                'abha_id'              => '847556789015',
                'abha_address'         => 'vivekprasad@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => ['NSAIDs'],
                    'chronic_conditions'   => ['Periodontitis Stage III', 'Diabetes Type 2'],
                    'current_medications'  => ['Metformin 500mg', 'Glimepiride 1mg'],
                ]),
                'family_history'       => json_encode(['diabetes' => 'Both parents']),
                'visit_count'          => 11,
                'last_visit_date'      => '2026-03-05',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic3,
                'name'                 => 'Ishita Sen',
                'dob'                  => '2002-01-08',
                'sex'                  => 'F',
                'phone'                => '+919742112233',
                'email'                => 'ishita.sen2002@gmail.com',
                'blood_group'          => 'O-',
                'abha_id'              => null,
                'abha_address'         => null,
                'abdm_consent_active'  => false,
                'medical_history'      => json_encode([
                    'allergies'            => [],
                    'chronic_conditions'   => ['Class II Malocclusion — Undergoing Orthodontic Treatment'],
                    'current_medications'  => [],
                ]),
                'family_history'       => null,
                'visit_count'          => 8,
                'last_visit_date'      => '2026-03-15',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic3,
                'name'                 => 'Mahesh Shetty',
                'dob'                  => '1973-05-22',
                'sex'                  => 'M',
                'phone'                => '+919741112233',
                'email'                => 'mahesh.shetty73@gmail.com',
                'blood_group'          => 'AB+',
                'abha_id'              => '958667890116',
                'abha_address'         => 'maheshshetty@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => [],
                    'chronic_conditions'   => ['Partially Edentulous — Implant Planned'],
                    'current_medications'  => [],
                ]),
                'family_history'       => null,
                'visit_count'          => 6,
                'last_visit_date'      => '2026-02-28',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic3,
                'name'                 => 'Rekha Mukherjee',
                'dob'                  => '1955-10-10',
                'sex'                  => 'F',
                'phone'                => '+919740112233',
                'email'                => 'rekha.mukherjee55@yahoo.com',
                'blood_group'          => 'A-',
                'abha_id'              => '069778901217',
                'abha_address'         => 'rekhamukherjee@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => ['Sulfa drugs'],
                    'chronic_conditions'   => ['Full Mouth Rehabilitation Needed', 'Osteoporosis', 'Hypertension'],
                    'current_medications'  => ['Amlodipine 5mg', 'Calcium + Vit D3'],
                ]),
                'family_history'       => json_encode(['osteoporosis' => 'Mother']),
                'visit_count'          => 4,
                'last_visit_date'      => '2026-01-30',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic3,
                'name'                 => 'Karthik Subramanian',
                'dob'                  => '1986-04-19',
                'sex'                  => 'M',
                'phone'                => '+919739112233',
                'email'                => 'karthik.sub86@gmail.com',
                'blood_group'          => 'B+',
                'abha_id'              => null,
                'abha_address'         => null,
                'abdm_consent_active'  => false,
                'medical_history'      => json_encode([
                    'allergies'            => [],
                    'chronic_conditions'   => ['Tooth Sensitivity', 'Enamel Erosion'],
                    'current_medications'  => [],
                ]),
                'family_history'       => null,
                'visit_count'          => 3,
                'last_visit_date'      => '2026-02-08',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic3,
                'name'                 => 'Divya Nambiar',
                'dob'                  => '1997-08-31',
                'sex'                  => 'F',
                'phone'                => '+919738112233',
                'email'                => 'divya.nambiar97@gmail.com',
                'blood_group'          => 'O+',
                'abha_id'              => '170889012318',
                'abha_address'         => 'divyanambiar@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => [],
                    'chronic_conditions'   => ['Dental Fluorosis', 'Mild Crowding'],
                    'current_medications'  => [],
                ]),
                'family_history'       => null,
                'visit_count'          => 2,
                'last_visit_date'      => '2026-01-22',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
            [
                'clinic_id'            => $clinic3,
                'name'                 => 'Pranav Hegde',
                'dob'                  => '1963-12-05',
                'sex'                  => 'M',
                'phone'                => '+919737112233',
                'email'                => 'pranav.hegde63@yahoo.com',
                'blood_group'          => 'AB-',
                'abha_id'              => '281990123419',
                'abha_address'         => 'pranavhegde@abdm',
                'abdm_consent_active'  => true,
                'medical_history'      => json_encode([
                    'allergies'            => ['NSAIDs'],
                    'chronic_conditions'   => ['Edentulous — Upper Arch (Complete Denture)', 'Hypertension'],
                    'current_medications'  => ['Losartan 50mg'],
                ]),
                'family_history'       => json_encode(['hypertension' => 'Father']),
                'visit_count'          => 9,
                'last_visit_date'      => '2026-03-03',
                'created_at'           => $now,
                'updated_at'           => $now,
            ],
        ];

        DB::table('patients')->insert($patients);

        $this->command->info('PatientSeeder: created ' . count($patients) . ' patients across 3 clinics.');
    }
}
